### ISSUE TITLE
Stochasticity and multi-start version of Bipartite

### ISSUE THREAD

**Issue by jajupmochi** [dbblumenthal/gedlib#10]
Hi Dear Dr. Blumenthal,  

I am using the Bipartite method. I am wondering is there any stochasticity involved in the implementation (i.e., random order of nodes when constructing cost matrix)? Moreover, is the multi-start version implemented (i.e., the `mBipartite` described in [1])?

I used the following settings to run Bipartite but see no randomness:
```
'lsape_model': 'ECBP', 
'max_num_solutions': 1,
'greedy_method': 'BASIC', 
'optimal': True,
'threads': 8,
'centrality_method': 'NONE',
'centrality_weight': 0.7,
'init_option': 'EAGER_WITHOUT_SHUFFLED_COPIES'
```
Can you tell me which parameters control these behaviors? Thanks a lot!

[1] Daller,  É., Bougleux, S., Gaüzère, B., & Brun, L. (2018, January).  Approximate graph edit distance by several local searches in parallel.  In 7th International Conference on Pattern Recognition Applications and Methods. [link](https://hal.archives-ouvertes.fr/hal-01664529/document)

**Comment by dbblumenthal** [comment]
The randomness comes from the storage order of the data, so you won't see it unless you explicitly shuffle it. There is a multi-start version, available for the heuristics that implement LSBasedMethod (--initial-solutions).

'lsape_model': 'ECBP', # controls LSAPE solver, you can keep the default
'max_num_solutions': 1, # controls number of optimal LSAPE solutions. if > 1, the min cost induced edit path is used
'greedy_method': 'BASIC',  # controls which kind of greedy method is used in a greedy LSAPE solver is used (I wouldn't use it, doesn't work too well)
'optimal': True, # controls if LSAPE is solved optimally or greedily (as mentioned above, I'd use the optimal solver)
'threads': 8, # number of threads used
'centrality_method': 'NONE', # add centrality scores to auxiliary bipartite graph
'centrality_weight': 0.7, # weight of centrality scores if used
'init_option': 'EAGER_WITHOUT_SHUFFLED_COPIES' # how to initialize the environment. EAGER/LAZY: do or do not precompute edit costs. WITH_SHUFFLED_COPIES/WITHOUT_SHUFFLED_COPIES: do or do not construct shuffled copies of all graphs (sometimes useful for testing if a methods finds GED(G,G) = 0)
