### ISSUE TITLE
Install error: AttributeError: 'Namespace' object has no attribute 'median'

### ISSUE THREAD

**Issue by jajupmochi** [dbblumenthal/gedlib#4]
Hi, when I install the library, I get an error message:
```
Traceback (most recent call last):
  File "install.py", line 223, in <module>
    if args.lib or args.tests or args.doc or args.median:
AttributeError: 'Namespace' object has no attribute 'median'
```
I think it is a bug [here](https://github.com/dbblumenthal/gedlib/blob/master/install.py#L223). 

Thanks.

**Comment by tiankonghenlan20113046** [comment]
Hi, friend:
could you please give me some recommendations about s**ource code tutorials by a video or other materials about calculating GED**, I have found lots of sources, but it was in vain. 
Hopefully to your reply.
-coder from Github.

**Comment by dbblumenthal** [comment]
Thanks, I fixed it.
