### ISSUE TITLE
NameError: name 'components' is not defined

### ISSUE THREAD

**Issue by tiankonghenlan20113046** [dbblumenthal/gedlib#6]
Hello, some errors about a script:
1. Traceback (most recent call last):
  File "**analyze_dataset.py**", line 148, in <module>
    nums_components = np.append(nums_components, [components])
**NameError: name 'components' is not defined**
2. graphs (total / not filtered): 1500 / 71
nodes (min / max / mean / std / median): 2 & 7 & 6.056338028169014 & 1.2408214323430145 & 6.0
edges (min / max / mean / std / median): 1 & 8 & 5.422535211267606 & 1.6094539609177652 & 6.0
Traceback (most recent call last):
  File "**analyze_dataset.py**", line 164, in <module>
    hist = as_2d_hist(min_num_nodes, max_num_nodes, min_num_edges, max_num_edges, nums_nodes, nums_edges)
**NameError: name 'min_num_nodes' is not defined**

**Comment by dbblumenthal** [comment]
Now it should work. Sorry for answering so late, I didn't see the issue.
