### ISSUE TITLE
Edit cost Fingerprint does not consider some attributes

### ISSUE THREAD

**Issue by jajupmochi** [dbblumenthal/gedlib#7]
Hi, I am using the edit cost [Fingerprint](https://github.com/dbblumenthal/gedlib/blob/master/src/edit_costs/fingerprint.ipp). In the implementation, only the edge attribute "orient" is considered in [edge_rel_cost_fun](https://github.com/dbblumenthal/gedlib/blob/master/src/edit_costs/fingerprint.ipp#L82). I wonder why the edge attribute "angle" is not used? Also [node_rel_cost_fun](https://github.com/dbblumenthal/gedlib/blob/master/src/edit_costs/fingerprint.ipp#L61) returns 0, where the node attributes "x" and "y" are not considered. Can I ask why and is there a way to add these attributes? Thanks!

**Comment by dbblumenthal** [comment]
Sorry for replying so late. I implemented the cost function defined by Kasper Riesen, who published the Fingerprint dataset (see reference in comments). You can modify the costs to your liking.
